import json

# Minimal data for the 118 elements in Spanish
elements = [
    {"num":1,"sym":"H","name":"Hidrógeno","mass":1.008,"group":1,"period":1,"category":"no metal"},
    {"num":2,"sym":"He","name":"Helio","mass":4.0026,"group":18,"period":1,"category":"gas noble"},
    {"num":3,"sym":"Li","name":"Litio","mass":6.94,"group":1,"period":2,"category":"metal alcalino"},
    {"num":4,"sym":"Be","name":"Berilio","mass":9.0122,"group":2,"period":2,"category":"alcalinotérreo"},
    {"num":5,"sym":"B","name":"Boro","mass":10.81,"group":13,"period":2,"category":"metaloide"},
    {"num":6,"sym":"C","name":"Carbono","mass":12.011,"group":14,"period":2,"category":"no metal"},
    {"num":7,"sym":"N","name":"Nitrógeno","mass":14.007,"group":15,"period":2,"category":"no metal"},
    {"num":8,"sym":"O","name":"Oxígeno","mass":15.999,"group":16,"period":2,"category":"no metal"},
    {"num":9,"sym":"F","name":"Flúor","mass":18.998,"group":17,"period":2,"category":"halógeno"},
    {"num":10,"sym":"Ne","name":"Neón","mass":20.180,"group":18,"period":2,"category":"gas noble"},
    {"num":11,"sym":"Na","name":"Sodio","mass":22.990,"group":1,"period":3,"category":"metal alcalino"},
    {"num":12,"sym":"Mg","name":"Magnesio","mass":24.305,"group":2,"period":3,"category":"alcalinotérreo"},
    {"num":13,"sym":"Al","name":"Aluminio","mass":26.982,"group":13,"period":3,"category":"metal del bloque p"},
    {"num":14,"sym":"Si","name":"Silicio","mass":28.085,"group":14,"period":3,"category":"metaloide"},
    {"num":15,"sym":"P","name":"Fósforo","mass":30.974,"group":15,"period":3,"category":"no metal"},
    {"num":16,"sym":"S","name":"Azufre","mass":32.06,"group":16,"period":3,"category":"no metal"},
    {"num":17,"sym":"Cl","name":"Cloro","mass":35.45,"group":17,"period":3,"category":"halógeno"},
    {"num":18,"sym":"Ar","name":"Argón","mass":39.95,"group":18,"period":3,"category":"gas noble"},
    {"num":19,"sym":"K","name":"Potasio","mass":39.098,"group":1,"period":4,"category":"metal alcalino"},
    {"num":20,"sym":"Ca","name":"Calcio","mass":40.078,"group":2,"period":4,"category":"alcalinotérreo"},
    {"num":21,"sym":"Sc","name":"Escandio","mass":44.956,"group":3,"period":4,"category":"metal de transición"},
    {"num":22,"sym":"Ti","name":"Titanio","mass":47.867,"group":4,"period":4,"category":"metal de transición"},
    {"num":23,"sym":"V","name":"Vanadio","mass":50.942,"group":5,"period":4,"category":"metal de transición"},
    {"num":24,"sym":"Cr","name":"Cromo","mass":51.996,"group":6,"period":4,"category":"metal de transición"},
    {"num":25,"sym":"Mn","name":"Manganeso","mass":54.938,"group":7,"period":4,"category":"metal de transición"},
    {"num":26,"sym":"Fe","name":"Hierro","mass":55.845,"group":8,"period":4,"category":"metal de transición"},
    {"num":27,"sym":"Co","name":"Cobalto","mass":58.933,"group":9,"period":4,"category":"metal de transición"},
    {"num":28,"sym":"Ni","name":"Níquel","mass":58.693,"group":10,"period":4,"category":"metal de transición"},
    {"num":29,"sym":"Cu","name":"Cobre","mass":63.546,"group":11,"period":4,"category":"metal de transición"},
    {"num":30,"sym":"Zn","name":"Zinc","mass":65.38,"group":12,"period":4,"category":"metal de transición"},
    {"num":31,"sym":"Ga","name":"Galio","mass":69.723,"group":13,"period":4,"category":"metal del bloque p"},
    {"num":32,"sym":"Ge","name":"Germanio","mass":72.630,"group":14,"period":4,"category":"metaloide"},
    {"num":33,"sym":"As","name":"Arsénico","mass":74.922,"group":15,"period":4,"category":"metaloide"},
    {"num":34,"sym":"Se","name":"Selenio","mass":78.971,"group":16,"period":4,"category":"no metal"},
    {"num":35,"sym":"Br","name":"Bromo","mass":79.904,"group":17,"period":4,"category":"halógeno"},
    {"num":36,"sym":"Kr","name":"Kriptón","mass":83.798,"group":18,"period":4,"category":"gas noble"},
    {"num":37,"sym":"Rb","name":"Rubidio","mass":85.468,"group":1,"period":5,"category":"metal alcalino"},
    {"num":38,"sym":"Sr","name":"Estroncio","mass":87.62,"group":2,"period":5,"category":"alcalinotérreo"},
    {"num":39,"sym":"Y","name":"Itrio","mass":88.906,"group":3,"period":5,"category":"metal de transición"},
    {"num":40,"sym":"Zr","name":"Circonio","mass":91.224,"group":4,"period":5,"category":"metal de transición"},
    {"num":41,"sym":"Nb","name":"Niobio","mass":92.906,"group":5,"period":5,"category":"metal de transición"},
    {"num":42,"sym":"Mo","name":"Molibdeno","mass":95.95,"group":6,"period":5,"category":"metal de transición"},
    {"num":43,"sym":"Tc","name":"Tecnecio","mass":98,"group":7,"period":5,"category":"metal de transición"},
    {"num":44,"sym":"Ru","name":"Rutenio","mass":101.07,"group":8,"period":5,"category":"metal de transición"},
    {"num":45,"sym":"Rh","name":"Rodio","mass":102.91,"group":9,"period":5,"category":"metal de transición"},
    {"num":46,"sym":"Pd","name":"Paladio","mass":106.42,"group":10,"period":5,"category":"metal de transición"},
    {"num":47,"sym":"Ag","name":"Plata","mass":107.87,"group":11,"period":5,"category":"metal de transición"},
    {"num":48,"sym":"Cd","name":"Cadmio","mass":112.41,"group":12,"period":5,"category":"metal de transición"},
    {"num":49,"sym":"In","name":"Indio","mass":114.82,"group":13,"period":5,"category":"metal del bloque p"},
    {"num":50,"sym":"Sn","name":"Estaño","mass":118.71,"group":14,"period":5,"category":"metal del bloque p"},
    {"num":51,"sym":"Sb","name":"Antimonio","mass":121.76,"group":15,"period":5,"category":"metaloide"},
    {"num":52,"sym":"Te","name":"Telurio","mass":127.60,"group":16,"period":5,"category":"metaloide"},
    {"num":53,"sym":"I","name":"Yodo","mass":126.90,"group":17,"period":5,"category":"halógeno"},
    {"num":54,"sym":"Xe","name":"Xenón","mass":131.29,"group":18,"period":5,"category":"gas noble"},
    {"num":55,"sym":"Cs","name":"Cesio","mass":132.91,"group":1,"period":6,"category":"metal alcalino"},
    {"num":56,"sym":"Ba","name":"Bario","mass":137.33,"group":2,"period":6,"category":"alcalinotérreo"},
    
    # Lantanidos (group 3, period 6 for visual purposes, but logically distinct)
    {"num":57,"sym":"La","name":"Lantano","mass":138.91,"group":3,"period":6,"category":"lantánido"},
    {"num":58,"sym":"Ce","name":"Cerio","mass":140.12,"group":3,"period":6,"category":"lantánido"},
    {"num":59,"sym":"Pr","name":"Praseodimio","mass":140.91,"group":3,"period":6,"category":"lantánido"},
    {"num":60,"sym":"Nd","name":"Neodimio","mass":144.24,"group":3,"period":6,"category":"lantánido"},
    {"num":61,"sym":"Pm","name":"Prometio","mass":145,"group":3,"period":6,"category":"lantánido"},
    {"num":62,"sym":"Sm","name":"Samario","mass":150.36,"group":3,"period":6,"category":"lantánido"},
    {"num":63,"sym":"Eu","name":"Europio","mass":151.96,"group":3,"period":6,"category":"lantánido"},
    {"num":64,"sym":"Gd","name":"Gadolinio","mass":157.25,"group":3,"period":6,"category":"lantánido"},
    {"num":65,"sym":"Tb","name":"Terbio","mass":158.93,"group":3,"period":6,"category":"lantánido"},
    {"num":66,"sym":"Dy","name":"Disprosio","mass":162.50,"group":3,"period":6,"category":"lantánido"},
    {"num":67,"sym":"Ho","name":"Holmio","mass":164.93,"group":3,"period":6,"category":"lantánido"},
    {"num":68,"sym":"Er","name":"Erbio","mass":167.26,"group":3,"period":6,"category":"lantánido"},
    {"num":69,"sym":"Tm","name":"Tulio","mass":168.93,"group":3,"period":6,"category":"lantánido"},
    {"num":70,"sym":"Yb","name":"Iterbio","mass":173.05,"group":3,"period":6,"category":"lantánido"},
    {"num":71,"sym":"Lu","name":"Lutecio","mass":174.97,"group":3,"period":6,"category":"lantánido"},

    {"num":72,"sym":"Hf","name":"Hafnio","mass":178.49,"group":4,"period":6,"category":"metal de transición"},
    {"num":73,"sym":"Ta","name":"Tántalo","mass":180.95,"group":5,"period":6,"category":"metal de transición"},
    {"num":74,"sym":"W","name":"Tungsteno","mass":183.84,"group":6,"period":6,"category":"metal de transición"},
    {"num":75,"sym":"Re","name":"Renio","mass":186.21,"group":7,"period":6,"category":"metal de transición"},
    {"num":76,"sym":"Os","name":"Osmio","mass":190.23,"group":8,"period":6,"category":"metal de transición"},
    {"num":77,"sym":"Ir","name":"Iridio","mass":192.22,"group":9,"period":6,"category":"metal de transición"},
    {"num":78,"sym":"Pt","name":"Platino","mass":195.08,"group":10,"period":6,"category":"metal de transición"},
    {"num":79,"sym":"Au","name":"Oro","mass":196.97,"group":11,"period":6,"category":"metal de transición"},
    {"num":80,"sym":"Hg","name":"Mercurio","mass":200.59,"group":12,"period":6,"category":"metal de transición"},
    {"num":81,"sym":"Tl","name":"Talio","mass":204.38,"group":13,"period":6,"category":"metal del bloque p"},
    {"num":82,"sym":"Pb","name":"Plomo","mass":207.2,"group":14,"period":6,"category":"metal del bloque p"},
    {"num":83,"sym":"Bi","name":"Bismuto","mass":208.98,"group":15,"period":6,"category":"metal del bloque p"},
    {"num":84,"sym":"Po","name":"Polonio","mass":209,"group":16,"period":6,"category":"metaloide"},
    {"num":85,"sym":"At","name":"Astato","mass":210,"group":17,"period":6,"category":"halógeno"},
    {"num":86,"sym":"Rn","name":"Radón","mass":222,"group":18,"period":6,"category":"gas noble"},
    {"num":87,"sym":"Fr","name":"Francio","mass":223,"group":1,"period":7,"category":"metal alcalino"},
    {"num":88,"sym":"Ra","name":"Radio","mass":226,"group":2,"period":7,"category":"alcalinotérreo"},
    
    # Actinidos
    {"num":89,"sym":"Ac","name":"Actinio","mass":227,"group":3,"period":7,"category":"actínido"},
    {"num":90,"sym":"Th","name":"Torio","mass":232.04,"group":3,"period":7,"category":"actínido"},
    {"num":91,"sym":"Pa","name":"Protactinio","mass":231.04,"group":3,"period":7,"category":"actínido"},
    {"num":92,"sym":"U","name":"Uranio","mass":238.03,"group":3,"period":7,"category":"actínido"},
    {"num":93,"sym":"Np","name":"Neptunio","mass":237,"group":3,"period":7,"category":"actínido"},
    {"num":94,"sym":"Pu","name":"Plutonio","mass":244,"group":3,"period":7,"category":"actínido"},
    {"num":95,"sym":"Am","name":"Americio","mass":243,"group":3,"period":7,"category":"actínido"},
    {"num":96,"sym":"Cm","name":"Curio","mass":247,"group":3,"period":7,"category":"actínido"},
    {"num":97,"sym":"Bk","name":"Berkelio","mass":247,"group":3,"period":7,"category":"actínido"},
    {"num":98,"sym":"Cf","name":"Californio","mass":251,"group":3,"period":7,"category":"actínido"},
    {"num":99,"sym":"Es","name":"Einstenio","mass":252,"group":3,"period":7,"category":"actínido"},
    {"num":100,"sym":"Fm","name":"Fermio","mass":257,"group":3,"period":7,"category":"actínido"},
    {"num":101,"sym":"Md","name":"Mendelevio","mass":258,"group":3,"period":7,"category":"actínido"},
    {"num":102,"sym":"No","name":"Nobelio","mass":259,"group":3,"period":7,"category":"actínido"},
    {"num":103,"sym":"Lr","name":"Lawrencio","mass":266,"group":3,"period":7,"category":"actínido"},

    {"num":104,"sym":"Rf","name":"Rutherfordio","mass":267,"group":4,"period":7,"category":"metal de transición"},
    {"num":105,"sym":"Db","name":"Dubnio","mass":268,"group":5,"period":7,"category":"metal de transición"},
    {"num":106,"sym":"Sg","name":"Seaborgio","mass":269,"group":6,"period":7,"category":"metal de transición"},
    {"num":107,"sym":"Bh","name":"Bohrio","mass":270,"group":7,"period":7,"category":"metal de transición"},
    {"num":108,"sym":"Hs","name":"Hassio","mass":269,"group":8,"period":7,"category":"metal de transición"},
    {"num":109,"sym":"Mt","name":"Meitnerio","mass":278,"group":9,"period":7,"category":"metal de transición"},
    {"num":110,"sym":"Ds","name":"Darmstadtio","mass":281,"group":10,"period":7,"category":"metal de transición"},
    {"num":111,"sym":"Rg","name":"Roentgenio","mass":282,"group":11,"period":7,"category":"metal de transición"},
    {"num":112,"sym":"Cn","name":"Copernicio","mass":285,"group":12,"period":7,"category":"metal de transición"},
    {"num":113,"sym":"Nh","name":"Nihonio","mass":286,"group":13,"period":7,"category":"metal del bloque p"},
    {"num":114,"sym":"Fl","name":"Flerovio","mass":289,"group":14,"period":7,"category":"metal del bloque p"},
    {"num":115,"sym":"Mc","name":"Moscovio","mass":290,"group":15,"period":7,"category":"metal del bloque p"},
    {"num":116,"sym":"Lv","name":"Livermorio","mass":293,"group":16,"period":7,"category":"metal del bloque p"},
    {"num":117,"sym":"Ts","name":"Teneso","mass":294,"group":17,"period":7,"category":"halógeno"},
    {"num":118,"sym":"Og","name":"Oganesón","mass":294,"group":18,"period":7,"category":"gas noble"},
]

content = f'''export const elements = {json.dumps(elements, indent=2)};
'''

with open('/Users/eddki11er/Documents/Apps Github/Iamequedo/src/data/periodicTableData.js', 'w', encoding='utf-8') as f:
    f.write(content)

print("Created src/data/periodicTableData.js")
